def get_historical_dns(start, end): ...
def get_historical_dos(start, end): ...
def load_predictions_from_sqlitecloud(type: str = "dns", time_window: str = "-24h") -> pd.DataFrame:
    # Query the appropriate table or add WHERE condition for data_type
    ...
API_URL_DNS = "http://your-fastapi-host/predict/dns"
API_URL_DOS = "http://your-fastapi-host/predict/dos"
def get_dns_data(): ...
def get_dos_data(): ...
